# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5850f04db9b8472a09c0833a8dddfec66e4753b38d203171efebe4bd1b55b7c2d51ce96b82774624cde84251db34dc37289375946ed70de2ba76c65df2077cbd

test:
  secret_key_base: fc53b72137f1dad9464abc602a0255dabd75f7b462c115520b0e92dd9f1129ede64b4181e4e60b2bc15b882b7b7b1d5189abe7e85fe90c7a1a993517e979ff8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
